### ISSUE TITLE
Keep settings after restart

### ISSUE THREAD

**Issue by theblackhole** [xflux-gui/fluxgui#34] opened 2016-10-03 09:18 UTC
Currently, if you set a lat./long. position and change other settings, it wont keep them after restart (with autostart).

_fluxgui 1.1.9~20160808-g4125e70-1~xenial_
_Linux Mint 18 Cinnamon x64_

**Comment by bholagabbar** [comment] 2016-11-15 14:29
@theblackhole I'm facing all the exact issues you're facing too. Do you have the dev capacity to collaborate? We could work on this together.

**Comment by bholagabbar** [comment] 2016-11-15 14:32
@theblackhole I'm thinking we can keep a .txt file keeping track of the details entered the first time and we could implement the logic to check for these when the code starts up. If yes, then pick up the details from there and continue.

**Comment by ntc2** [comment] 2016-11-15 20:10
@bholagabbar, I would be happy to help merge a pull request :D The settings are stored in gconf so you won't need to add a new .txt file. E.g. here is some related code, where you can see that latitude and longitude are already stored in gconf, and checked for on startup:

https://github.com/xflux-gui/xflux-gui/blob/8140fcdb2a697da87535a7e55cef37456d2d83a0/src/fluxgui/settings.py#L61

So, there must be some logic bug that causes the lat/long values to get erased or ignored in some cases. Hopefully an easy fix once you identify the cause ...

**Comment by bholagabbar** [comment] 2016-11-15 21:09
@ntc2 That's strange. I'm on Linux Mint running cinnamon and yeah it asks me for the coords everything. Does it ask you on your system? What system are you on?

**Comment by ntc2** [comment] 2016-11-15 23:37
@bholagabbar, I use xflux-gui with Ubuntu (xmonad + Gnome). I don't set latitude and longitude myself -- I use the the zip code setting -- which is probably why I haven't experienced this bug myself.

**Comment by bholagabbar** [comment] 2016-11-16 05:32
@ntc2  I see. If it's not too much trouble, could you set it to latitude-longitude, restart your system and see if you're experiencing the same bug? If yes, then we know that it's not specific to mint per say

**Comment by ntc2** [comment] 2016-11-16 07:37
@bholagabbar <https://github.com/bholagabbar>, I tried set the latitude and
longitude both to 100, unset the zip code, and restarted: all three
settings were saved and restored. I still doubt it's specific to Mint. You
could use `gconftool` to see what's being stored in your settings (i.e. are
the latitude and longitude set?). See comments near the code I linked you
to earlier for how to use `gconftool` to get this info.

I'm going to be offline for a few days, perhaps a week, starting tomorrow.

**Comment by bholagabbar** [comment] 2016-11-16 07:57
@ntc2 Thanks! I'll work on it when I find the time and let you know

**Comment by Kilian** [comment] 2016-11-16 10:11
AFAIK gconftool is being phased out in favor of dconftool. Don't ask me specifics, but could that be related? Great that you guys wanna pick this up :)

**Comment by simmel** [comment] 2016-11-25 14:47
Seems there are more people having this problem http://askubuntu.com/questions/327301/gconftool2-settings-arent-saved-permanently

This looks more and more like a gconf bug to me. None of the settings persists over a logout/login for me, I'm on Ubuntu xenial too. I never had this problem in trusty.

How to reproduce:
* Change to your wanted settings
* Quit Flux
* Check periodically that the settings are written to disk (`~/.gconf/apps/fluxgui/%gconf.xml`)
* When they are logout and login
* Login
* flux will start and none of the settings are persisted
* `gconftool -a /apps/fluxgui` will show the defaults
* `~/.gconf/apps/fluxgui/%gconf.xml` will include your wanted settings.
* After a while `~/.gconf/apps/fluxgui/%gconf.xml` will include the defaults not your wanted settings.

**Comment by theblackhole** [comment] 2016-11-25 20:15
> @theblackhole I'm facing all the exact issues you're facing too. Do you have the dev capacity to collaborate? We could work on this together.

Sorry for my late response. And sorry again : I'm a web dev and I just do small sh scripts too but I've never developed a linux app. That's why I opened an issue, this is the only way I could help.

**Comment by bholagabbar** [comment] 2016-11-27 14:02
@simmel @nt2c alright I'm gonna try and rewrite the same in dconftool instead of gconftool and see if that makes a difference. It's great that we have a reproduction method which doesn't involve restarting the system to say the least

**Comment by ntc2** [comment] 2016-11-27 22:33
@bholagabbar, awesome!

**Comment by Kilian** [comment] 2016-11-28 08:23
switching to dconf would be nice!

**Comment by bil-elmoussaoui** [comment] 2017-01-17 03:47
Is there anyone working on using dconf instead of gconf? if not i would like to take this one!

**Comment by ntc2** [comment] 2017-01-17 05:22
@bil-elmoussaoui , I don't think anyone is working on it -- it's been a month and a half since we heard anything -- so please give it a shot!

**Comment by oyhel** [comment] 2017-02-18 12:59
The problem with fluxgui not storing changes can be fixed by changig the permissions on ~/.gconf/apps and ~/.gconf/schemas to the user. Both were set to root after a fresh install of ubuntu 16.04.2. After changing the permissions and resetting fluxgui location it persists across boots.

**Comment by simmel** [comment] 2017-02-18 19:22
I can't belive I didn't notice that before. Thank you Øyvind! Have a
great weekend!

**Comment by ntc2** [comment] 2018-12-27 06:52
Hopefully this is fixed by #112. Please let me know if it is not.

**Closed by ntc2** 2018-12-27 06:52 UTC
Labels: bug, help wanted
