### ISSUE TITLE
f.lux not working anymore on ubuntu-16.04

### ISSUE THREAD

**Issue by pavanyogi** [xflux-gui/fluxgui#129] opened 2019-10-20 07:50 UTC
Before opening a new issue for a bug, please:

1. Check that you're not experiencing an existing issue. In particular, [Issue #27](https://github.com/xflux-gui/xflux-gui/issues/27) is very common.

2. Install `xflux-gui` from source if you used the PPA and the PPA is stale. This [is easy to do](https://github.com/xflux-gui/xflux-gui/blob/master/README.md) and ensures your issue isn't already fixed.

Thanks!

**Comment by pavanyogi** [comment] 2019-10-20 07:52
I installed f.lux recently. But I didn't see any difference on the screen before and after the installation. seems like f.lux not working on the Ubuntu-16.04. Please revert back here if anyone got it working on Ubuntu-16.04.

**Comment by pavanyogi** [comment] 2019-10-20 07:54
before f.lux install 
![Screenshot from 2019-10-20 13-14-02](https://user-images.githubusercontent.com/13834016/67156507-f2e21180-f33c-11e9-97a2-23f41e1375cb.png)
after f.lux install
![Screenshot from 2019-10-20 13-14-02](https://user-images.githubusercontent.com/13834016/67156516-ffff0080-f33c-11e9-9ef0-39527fbbbcb7.png)

**Comment by amrithmmh** [comment] 2019-11-02 05:20
did you run flux? it wont start automatically on install

**Comment by pavanyogi** [comment] 2019-11-03 15:19
Yes I run it.

**Comment by Minabsapi** [comment] 2019-12-06 21:21
I got the same problem on Ubuntu 19.04 disco (x86-64)
Installed from the PPA, running, but when I try to preview anything there's absolutely no difference. I will tell later if a reboot fixed.

**Comment by Minabsapi** [comment] 2019-12-09 08:04
The reboot didn't fix. It's definitly not working for me neither.

**Comment by pavanyogi** [comment] 2019-12-09 10:38
It won't work for Ubuntu-16.04 or greater. I switched to redshift. Follow the article from here: https://linoxide.com/tools/install-use-redshift-ubuntu-16-04/

**Comment by Minabsapi** [comment] 2019-12-09 15:16
Alright, I will try it. Thank you !

**Comment by penguinstampede** [comment] 2019-12-31 00:55
FWIW - working on Kubuntu 19.04

**Comment by rankela** [comment] 2020-01-09 16:24
I have the same issue on 16.04. When running from terminal I get the following assertion error when I try to preview the color:
/usr/lib/python3/dist-packages/fluxgui/fluxapp.py:53: Warning: g_object_set_data: assertion 'G_IS_OBJECT (object)' failed
  gtk.main()

**Comment by ntc2** [comment] 2020-03-04 03:14
Duplicate of #27

**Closed by ntc2** 2020-03-04 03:14 UTC
